name: macos-test
on:
  workflow_dispatch:
jobs:
  get-macos-info:
    runs-on: macos-13
    steps:
      - name: info
        run: |
          if [ $(uname -m) != "x86_64" ]
          then
              sysctl hw
              echo "$(uname -m) detected"
              exit -1
          fi
